# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\"#\n\x08UserRole\x12\x17\n\x04role\x18\x01 \x01(\x0e\x32\t.RoleType\"C\n\x07\x41rticle\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x1a\n\x04type\x18\x03 \x01(\x0e\x32\x0c.ArticleType*2\n\x08RoleType\x12\x11\n\rDIRECTOR_ROLE\x10\x00\x12\x13\n\x0f\x41\x43\x43OUNTANT_ROLE\x10\x01*2\n\x0b\x41rticleType\x12\x0b\n\x07INSIDER\x10\x00\x12\n\n\x06TRANDE\x10\x01\x12\n\n\x06\x44IGEST\x10\x02\x32%\n\x03\x41pi\x12\x1e\n\x07getNews\x12\t.UserRole\x1a\x08.Articleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLETYPE._serialized_start=119
  _ROLETYPE._serialized_end=169
  _ARTICLETYPE._serialized_start=171
  _ARTICLETYPE._serialized_end=221
  _USERROLE._serialized_start=13
  _USERROLE._serialized_end=48
  _ARTICLE._serialized_start=50
  _ARTICLE._serialized_end=117
  _API._serialized_start=223
  _API._serialized_end=260
# @@protoc_insertion_point(module_scope)
