# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parser.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparser.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x0bPureArticle\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2;\n\x06Parser\x12\x31\n\x07getNews\x12\x16.google.protobuf.Empty\x1a\x0c.PureArticle0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parser_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUREARTICLE._serialized_start=45
  _PUREARTICLE._serialized_end=88
  _PARSER._serialized_start=90
  _PARSER._serialized_end=149
# @@protoc_insertion_point(module_scope)
