# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x1a\x1bgoogle/protobuf/empty.proto\"B\n\rHandleArticle\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x13\n\x04role\x18\x03 \x01(\x0e\x32\x05.Role*$\n\x04Role\x12\x0c\n\x08\x44IRECTOR\x10\x00\x12\x0e\n\nACCOUNTANT\x10\x01\x32\x41\n\nController\x12\x33\n\x07getNews\x12\x16.google.protobuf.Empty\x1a\x0e.HandleArticle0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLE._serialized_start=117
  _ROLE._serialized_end=153
  _HANDLEARTICLE._serialized_start=49
  _HANDLEARTICLE._serialized_end=115
  _CONTROLLER._serialized_start=155
  _CONTROLLER._serialized_end=220
# @@protoc_insertion_point(module_scope)
